"""
Alfa-2 Agent — Satellite Thermal Anomaly Detection (Historical Baseline)
===========================================================================
Role: Senior Satellite Thermal Analyst (30 years experience)
Mission: Detect thermal anomalies using ONLY pre-trained historical baselines.
         NO live training, NO online learning. All baselines computed offline
         from satellite history (tbl_cobertura_satelital_historico / tbl_cobertura_satelital).
"""

from typing import Any, Dict, List, Optional
import json
import numpy as np
from pathlib import Path
from sentinel_omega.core.shared.agent_base import BaseAgent, AgentSignal, SignalType


class Alfa2Agent(BaseAgent):
    """
    Alfa-2 operates in PURE INFERENCE MODE.
    Baseline statistics (mean, std per zona) are loaded from a precomputed JSON file
    generated by the training pipeline. This ensures ZERO live training in production.
    """
    
    def __init__(self):
        super().__init__(name="alfa2", layer="geodynamic")
        self._cobertura_data: Optional[Dict[str, Any]] = None
        self._baseline_stats: Optional[Dict[str, Dict[str, float]]] = None
        self._historical_baseline_path = Path("/home/deamon/workspaces/sentinel_omega/data/alfa2_baseline_historical.json")
        self._load_historical_baseline()

    def _load_historical_baseline(self) -> None:
        """Load precomputed historical baseline from training pipeline."""
        try:
            if self._historical_baseline_path.exists():
                with open(self._historical_baseline_path) as f:
                    self._baseline_stats = json.load(f)
                self.logger.info(f"Alfa-2: Loaded historical baseline for {len(self._baseline_stats)} zones")
            else:
                # Sin JSON, calcular el baseline de las zonas REALES desde el
                # histórico antes de recurrir a los valores por defecto, que
                # describen zonas genéricas ("mexico", "peru"...) y no las que
                # el pipeline observa (guerrero_gap, oaxaca_costa, chiapas).
                # Medido 2026-09-21: claridad real 0.21-0.33 frente al 0.65 del
                # default, así que alfa2 leía nubosidad normal como anomalía.
                self._baseline_stats = self._baseline_desde_db()
                if self._baseline_stats:
                    self.logger.info(
                        "Alfa-2: baseline calculado desde el histórico (%d zonas)",
                        len(self._baseline_stats),
                    )
                else:
                    self.logger.warning("Alfa-2: sin histórico, usando defaults")
                    self._baseline_stats = self._default_baseline()
        except Exception as e:
            self.logger.error(f"Alfa-2: Failed to load baseline: {e}")
            self._baseline_stats = self._default_baseline()

    def _baseline_desde_db(self) -> Optional[Dict[str, Dict[str, float]]]:
        """Media y desviación reales por zona desde tbl_cobertura_satelital_historico."""
        import sqlite3
        import statistics
        db = self._historical_baseline_path.parent / "SENTINEL_OMEGA_PRO.db"
        if not db.exists():
            return None
        try:
            con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
            filas = con.execute(
                "SELECT zona, thermal_anomalies, clear_passes, total_passes "
                "FROM tbl_cobertura_satelital_historico WHERE total_passes > 0"
            ).fetchall()
            con.close()
        except Exception as exc:
            self.logger.warning("Alfa-2: no se pudo leer el histórico: %s", exc)
            return None

        acum: Dict[str, Dict[str, list]] = {}
        for zona, thermal, clear, total in filas:
            z = str(zona).lower()
            clarity = (clear or 0) / total
            obs = total * (0.5 + 0.5 * clarity)
            d = acum.setdefault(z, {"obs": [], "th": [], "cl": []})
            d["obs"].append(obs)
            d["th"].append(float(thermal or 0))
            d["cl"].append(clarity)

        def _ms(v):
            return (statistics.fmean(v), statistics.pstdev(v) if len(v) > 1 else 0.0)

        out: Dict[str, Dict[str, float]] = {}
        for z, d in acum.items():
            if len(d["obs"]) < 30:      # muestra insuficiente para un baseline
                continue
            om, os_ = _ms(d["obs"]); tm, ts = _ms(d["th"]); cm, cs = _ms(d["cl"])
            out[z] = {"obs_mean": om, "obs_std": os_, "thermal_mean": tm,
                      "thermal_std": ts, "clarity_mean": cm, "clarity_std": cs}
        return out or None

    @staticmethod
    def _z(valor: float, mean: float, std: float, tope: float = 6.0) -> float:
        """z-score acotado, honesto cuando no hay varianza histórica.

        thermal_std es 0.000 en las tres zonas reales (2.690 registros sin una
        sola anomalía térmica). Dividir por el epsilon de 0.01 convertía la
        primera anomalía en 200σ. Sin varianza medida, una desviación es
        significativa pero su magnitud NO es medible: se reporta como 3σ.
        """
        if std <= 1e-9:
            return 0.0 if abs(valor - mean) <= 1e-9 else 3.0
        return max(-tope, min(tope, (valor - mean) / std))

    def _default_baseline(self) -> Dict[str, Dict[str, float]]:
        """Fallback defaults if baseline file missing."""
        return {
            "mexico": {"obs_mean": 2.5, "obs_std": 1.2, "thermal_mean": 0.8, "thermal_std": 0.4, "clarity_mean": 0.65, "clarity_std": 0.15},
            "peru": {"obs_mean": 3.1, "obs_std": 1.5, "thermal_mean": 1.1, "thermal_std": 0.5, "clarity_mean": 0.72, "clarity_std": 0.12},
            "chile": {"obs_mean": 2.8, "obs_std": 1.3, "thermal_mean": 0.9, "thermal_std": 0.45, "clarity_mean": 0.68, "clarity_std": 0.14},
            "japon": {"obs_mean": 3.5, "obs_std": 1.6, "thermal_mean": 1.3, "thermal_std": 0.6, "clarity_mean": 0.75, "clarity_std": 0.10},
            "indonesia": {"obs_mean": 3.2, "obs_std": 1.4, "thermal_mean": 1.0, "thermal_std": 0.5, "clarity_mean": 0.70, "clarity_std": 0.13},
            "turquia": {"obs_mean": 2.9, "obs_std": 1.3, "thermal_mean": 0.95, "thermal_std": 0.4, "clarity_mean": 0.66, "clarity_std": 0.15},
            "california": {"obs_mean": 2.6, "obs_std": 1.1, "thermal_mean": 0.85, "thermal_std": 0.35, "clarity_mean": 0.64, "clarity_std": 0.16},
            "italia": {"obs_mean": 2.4, "obs_std": 1.0, "thermal_mean": 0.75, "thermal_std": 0.3, "clarity_mean": 0.62, "clarity_std": 0.17},
        }

    def ingest(self, data: Dict[str, Any]) -> None:
        # El pipeline entrega "zone_coverages"; este agente leía solo
        # "cobertura_satelital" y el .get(k, {}) devolvía {} en silencio, así
        # que analyze() caía siempre en NO_SIGNAL 0.0 pese a haber cobertura
        # real en la DB. Los tests no lo detectaban porque llaman a ingest()
        # con la clave del agente, nunca con la del pipeline.
        self._cobertura_data = (
            data.get("zone_coverages")
            or data.get("cobertura_satelital")
            or {}
        )
        n = len(self._cobertura_data)
        self.logger.info(f"Alfa-2 (Satellite) ingested: {n} zone records")

    def _compute_observation_index(self, zone_data: Dict[str, Any]) -> float:
        """Compute observation index: total_passes * (0.5 + 0.5 * clarity)"""
        total_passes = zone_data.get("total_passes", 0)
        clear_passes = zone_data.get("clear_passes", 0)
        clarity = clear_passes / total_passes if total_passes > 0 else 0.0
        return total_passes * (0.5 + 0.5 * clarity)

    def _compute_anomaly_score(self, zona: str, zone_data: Dict[str, Any]) -> Dict[str, float]:
        """Compute sigma deviation from historical baseline."""
        stats = self._baseline_stats.get(zona.lower(), self._default_baseline().get("mexico"))
        
        obs_idx = self._compute_observation_index(zone_data)
        thermal = zone_data.get("thermal_anomalies", 0.0)
        clarity = zone_data.get("clear_passes", 0) / zone_data.get("total_passes", 1) if zone_data.get("total_passes", 0) > 0 else 0.0
        
        # Z-scores
        z_obs = self._z(obs_idx, stats["obs_mean"], stats["obs_std"])
        z_thermal = self._z(thermal, stats["thermal_mean"], stats["thermal_std"])
        z_clarity = self._z(clarity, stats["clarity_mean"], stats["clarity_std"])
        
        # Combined anomaly (weighted)
        # Solo cuentan las desviaciones que significan MÁS actividad. Una
        # caída de obs/clarity es cobertura degradada (nubes, menos pases del
        # satélite), no un precursor: con abs() el sistema emitía ALERT 0.95
        # por tener menos imágenes de las habituales.
        combined_sigma = max(
            max(0.0, z_obs),
            abs(z_thermal) * 1.2,
            max(0.0, z_clarity) * 0.8,
        )
        cobertura_degradada = z_obs <= -2.0 or z_clarity <= -2.0
        
        return {
            "zona": zona,
            "observation_index": round(obs_idx, 2),
            "z_obs": round(z_obs, 2),
            "z_thermal": round(z_thermal, 2),
            "z_clarity": round(z_clarity, 2),
            "combined_sigma": round(combined_sigma, 2),
            "thermal_anomalies": thermal,
            "clarity": round(clarity, 3),
            "cobertura_degradada": cobertura_degradada,
            "baseline_used": stats
        }

    def analyze(self) -> AgentSignal:
        if not self._cobertura_data:
            return self.emit_signal(SignalType.NO_SIGNAL, 0.0, reasoning="No satellite coverage data")

        anomalies = []
        max_sigma = 0.0
        peor_zona = "—"
        degradadas = []

        for zona, zone_data in self._cobertura_data.items():
            anomaly = self._compute_anomaly_score(zona, zone_data)
            anomalies.append(anomaly)
            if anomaly["combined_sigma"] > max_sigma:
                max_sigma = anomaly["combined_sigma"]
                peor_zona = zona
            if anomaly.get("cobertura_degradada"):
                degradadas.append(zona)

        # La cobertura degradada se informa, no altera la señal: menos pases o
        # más nubes es un problema de observación, no un precursor.
        if degradadas:
            self.logger.info(
                "Alfa-2: cobertura degradada en %s (no eleva la señal)",
                ", ".join(degradadas),
            )

        # Signal logic based on sigma deviations
        if max_sigma >= 3.0:
            signal_type = SignalType.ALERT
            confidence = min(0.95, 0.6 + max_sigma * 0.1)
            reasoning = f"CRITICAL satellite anomaly: {max_sigma:.1f}σ over baseline (zona={peor_zona})"
        elif max_sigma >= 2.0:
            signal_type = SignalType.WATCH
            confidence = min(0.8, 0.4 + max_sigma * 0.1)
            reasoning = f"ELEVATED satellite anomaly: {max_sigma:.1f}σ over baseline (zona={peor_zona})"
        elif max_sigma >= 1.0:
            signal_type = SignalType.WATCH
            confidence = 0.35
            reasoning = f"MODERATE satellite anomaly: {max_sigma:.1f}σ over baseline (zona={peor_zona})"
        else:
            signal_type = SignalType.NEUTRAL
            confidence = 0.2
            reasoning = "No significant thermal anomalies detected vs historical baseline"

        signal_data = {
            "anomalies": anomalies,
            "max_sigma": round(max_sigma, 2),
            "zones_analyzed": len(anomalies),
            "baseline_source": "historical_precomputed"
        }

        return self.emit_signal(signal_type, confidence, data=signal_data, reasoning=reasoning)

    def health_check(self) -> bool:
        return self._baseline_stats is not None and len(self._baseline_stats) > 0

