"""
Alfa-2 Agent — Satellite Thermal Anomaly Detection (Historical Baseline)
===========================================================================
Role: Senior Satellite Thermal Analyst (30 years experience)
Mission: Detect thermal anomalies using ONLY pre-trained historical baselines.
         NO live training, NO online learning. All baselines computed offline
         from satellite history (tbl_cobertura_satelital_historico / tbl_cobertura_satelital).
"""

from typing import Any, Dict, List, Optional
import json
import numpy as np
from pathlib import Path
from sentinel_omega.core.shared.agent_base import BaseAgent, AgentSignal, SignalType


class Alfa2Agent(BaseAgent):
    """
    Alfa-2 operates in PURE INFERENCE MODE.
    Baseline statistics (mean, std per zona) are loaded from a precomputed JSON file
    generated by the training pipeline. This ensures ZERO live training in production.
    """
    
    def __init__(self):
        super().__init__(name="alfa2", layer="geodynamic")
        self._cobertura_data: Optional[Dict[str, Any]] = None
        self._baseline_stats: Optional[Dict[str, Dict[str, float]]] = None
        self._historical_baseline_path = Path("/home/deamon/workspaces/sentinel_omega/data/alfa2_baseline_historical.json")
        self._load_historical_baseline()

    def _load_historical_baseline(self) -> None:
        """Load precomputed historical baseline from training pipeline."""
        try:
            if self._historical_baseline_path.exists():
                with open(self._historical_baseline_path) as f:
                    self._baseline_stats = json.load(f)
                self.logger.info(f"Alfa-2: Loaded historical baseline for {len(self._baseline_stats)} zones")
            else:
                self.logger.warning("Alfa-2: Historical baseline file not found, using defaults")
                self._baseline_stats = self._default_baseline()
        except Exception as e:
            self.logger.error(f"Alfa-2: Failed to load baseline: {e}")
            self._baseline_stats = self._default_baseline()

    def _default_baseline(self) -> Dict[str, Dict[str, float]]:
        """Fallback defaults if baseline file missing."""
        return {
            "mexico": {"obs_mean": 2.5, "obs_std": 1.2, "thermal_mean": 0.8, "thermal_std": 0.4, "clarity_mean": 0.65, "clarity_std": 0.15},
            "peru": {"obs_mean": 3.1, "obs_std": 1.5, "thermal_mean": 1.1, "thermal_std": 0.5, "clarity_mean": 0.72, "clarity_std": 0.12},
            "chile": {"obs_mean": 2.8, "obs_std": 1.3, "thermal_mean": 0.9, "thermal_std": 0.45, "clarity_mean": 0.68, "clarity_std": 0.14},
            "japon": {"obs_mean": 3.5, "obs_std": 1.6, "thermal_mean": 1.3, "thermal_std": 0.6, "clarity_mean": 0.75, "clarity_std": 0.10},
            "indonesia": {"obs_mean": 3.2, "obs_std": 1.4, "thermal_mean": 1.0, "thermal_std": 0.5, "clarity_mean": 0.70, "clarity_std": 0.13},
            "turquia": {"obs_mean": 2.9, "obs_std": 1.3, "thermal_mean": 0.95, "thermal_std": 0.4, "clarity_mean": 0.66, "clarity_std": 0.15},
            "california": {"obs_mean": 2.6, "obs_std": 1.1, "thermal_mean": 0.85, "thermal_std": 0.35, "clarity_mean": 0.64, "clarity_std": 0.16},
            "italia": {"obs_mean": 2.4, "obs_std": 1.0, "thermal_mean": 0.75, "thermal_std": 0.3, "clarity_mean": 0.62, "clarity_std": 0.17},
        }

    def ingest(self, data: Dict[str, Any]) -> None:
        self._cobertura_data = data.get("cobertura_satelital", {})
        n = len(self._cobertura_data)
        self.logger.info(f"Alfa-2 (Satellite) ingested: {n} zone records")

    def _compute_observation_index(self, zone_data: Dict[str, Any]) -> float:
        """Compute observation index: total_passes * (0.5 + 0.5 * clarity)"""
        total_passes = zone_data.get("total_passes", 0)
        clear_passes = zone_data.get("clear_passes", 0)
        clarity = clear_passes / total_passes if total_passes > 0 else 0.0
        return total_passes * (0.5 + 0.5 * clarity)

    def _compute_anomaly_score(self, zona: str, zone_data: Dict[str, Any]) -> Dict[str, float]:
        """Compute sigma deviation from historical baseline."""
        stats = self._baseline_stats.get(zona.lower(), self._default_baseline().get("mexico"))
        
        obs_idx = self._compute_observation_index(zone_data)
        thermal = zone_data.get("thermal_anomalies", 0.0)
        clarity = zone_data.get("clear_passes", 0) / zone_data.get("total_passes", 1) if zone_data.get("total_passes", 0) > 0 else 0.0
        
        # Z-scores
        z_obs = (obs_idx - stats["obs_mean"]) / max(stats["obs_std"], 0.01)
        z_thermal = (thermal - stats["thermal_mean"]) / max(stats["thermal_std"], 0.01)
        z_clarity = (clarity - stats["clarity_mean"]) / max(stats["clarity_std"], 0.01)
        
        # Combined anomaly (weighted)
        combined_sigma = max(abs(z_obs), abs(z_thermal) * 1.2, abs(z_clarity) * 0.8)
        
        return {
            "zona": zona,
            "observation_index": round(obs_idx, 2),
            "z_obs": round(z_obs, 2),
            "z_thermal": round(z_thermal, 2),
            "z_clarity": round(z_clarity, 2),
            "combined_sigma": round(combined_sigma, 2),
            "thermal_anomalies": thermal,
            "clarity": round(clarity, 3),
            "baseline_used": stats
        }

    def analyze(self) -> AgentSignal:
        if not self._cobertura_data:
            return self.emit_signal(SignalType.NO_SIGNAL, 0.0, reasoning="No satellite coverage data")

        anomalies = []
        max_sigma = 0.0
        
        for zona, zone_data in self._cobertura_data.items():
            anomaly = self._compute_anomaly_score(zona, zone_data)
            anomalies.append(anomaly)
            max_sigma = max(max_sigma, anomaly["combined_sigma"])

        # Signal logic based on sigma deviations
        if max_sigma >= 3.0:
            signal_type = SignalType.ALERT
            confidence = min(0.95, 0.6 + max_sigma * 0.1)
            reasoning = f"CRITICAL thermal anomaly: {max_sigma:.1f}σ deviation from historical baseline"
        elif max_sigma >= 2.0:
            signal_type = SignalType.WATCH
            confidence = min(0.8, 0.4 + max_sigma * 0.1)
            reasoning = f"ELEVATED thermal anomaly: {max_sigma:.1f}σ deviation from historical baseline"
        elif max_sigma >= 1.0:
            signal_type = SignalType.WATCH
            confidence = 0.35
            reasoning = f"MODERATE thermal anomaly: {max_sigma:.1f}σ deviation from historical baseline"
        else:
            signal_type = SignalType.NEUTRAL
            confidence = 0.2
            reasoning = "No significant thermal anomalies detected vs historical baseline"

        signal_data = {
            "anomalies": anomalies,
            "max_sigma": round(max_sigma, 2),
            "zones_analyzed": len(anomalies),
            "baseline_source": "historical_precomputed"
        }

        return self.emit_signal(signal_type, confidence, data=signal_data, reasoning=reasoning)

    def health_check(self) -> bool:
        return self._baseline_stats is not None and len(self._baseline_stats) > 0

