"""
Beta-2 Agent — The Analyst (Cymatic Interpreter & Atmospheric Stress)
Role: Interpret the "Cymatic Figure" generated by Beta-1 and cross-reference it with
       historical patterns and atmospheric anomalies.

Method: 
  1. Receive cymatic_figure from Beta-1.
  2. Scan historical figures for similar patterns based on event magnitude.
  3. Weigh the figure against tectonic degassing and atmospheric stress.
  4. Determine if the current vibration is a known precursor to a specific magnitude.
"""

from typing import Any, Dict, List, Optional
import numpy as np
from sentinel_omega.core.shared.agent_base import BaseAgent, AgentSignal, SignalType


class Beta2Agent(BaseAgent):
    LOW_PRESSURE_THRESHOLD = 1008.0
    HIGH_SO2_THRESHOLD = 20.0
    FOG_VISIBILITY_THRESHOLD = 1000
    TRAINING_YEARS = 14

    MARINE_THERMAL_THRESHOLD_C = 29.0
    NODE_SO2_EXCESS_ALERT = 50.0
    NODE_CO_ALERT = 400.0

    def __init__(self):
        super().__init__(name="beta2", layer="geodynamic")
        self._pressure_gradient: Optional[Dict[str, Any]] = None
        self._air_quality: Optional[Dict[str, float]] = None
        self._atmospheric_readings: List[Dict[str, Any]] = []
        self._degassing_baseline: Optional[Dict[str, float]] = None
        self._global_node_scan: List[Dict[str, Any]] = []
        self._current_figure: Optional[Dict[str, Any]] = None

    def ingest(self, data: Dict[str, Any]) -> None:
        self._pressure_gradient = data.get("pressure_gradient")
        self._air_quality = data.get("air_quality")
        self._atmospheric_readings = data.get("atmospheric_readings", [])
        self._degassing_baseline = data.get("degassing_baseline")
        self._global_node_scan = data.get("global_node_scan", [])
        # Ingest the figure generated by Beta-1 (passed via orchestrator/data pipeline)
        self._current_figure = data.get("beta1_figure")
        
        n_stations = len(self._atmospheric_readings)
        self.logger.info(
            f"Beta-2 (Analyst) ingested: {n_stations} stations, "
            f"Figure present: {self._current_figure is not None}"
        )

    def _compare_figures(self, figure: Dict[str, Any]) -> Dict[str, Any]:
        """
        Compare the current figure against the historical cymatic library.
        In a real implementation, this queries TBL_CIMATICA_PATRONES.
        """
        match_found = False
        similar_magnitude = 0.0
        confidence = 0.0
        
        if figure.get("spectral_energy", 0) > 1e5 and figure.get("schumann_activity", 0) > 20:
            match_found = True
            similar_magnitude = 6.5
            confidence = 0.75
        
        return {
            "match_found": match_found,
            "similar_magnitude": similar_magnitude,
            "confidence": confidence,
            "pattern_id": "FIB-S6-SNT" if match_found else None
        }

    def _pressure_stress(self) -> float:
        if not self._pressure_gradient:
            return 0.0
        stress = 0.0
        mean_p = self._pressure_gradient.get("mean_pressure", 1013.0)
        if mean_p < self.LOW_PRESSURE_THRESHOLD:
            stress += (self.LOW_PRESSURE_THRESHOLD - mean_p) / 20.0
        spread = self._pressure_gradient.get("pressure_spread", 0.0)
        if spread > 10.0:
            stress += spread / 50.0
        return min(1.0, stress)

    def _degassing_signature(self) -> Dict[str, float]:
        aq = self._air_quality or {}
        base = self._degassing_baseline or {}
        so2 = aq.get("so2", 0.0)
        no2 = aq.get("no2", 0.0)
        so2_excess = max(0.0, so2 - base.get("so2", 0.0))
        no2_excess = max(0.0, no2 - base.get("no2", 0.0))
        tectonic_purity = so2_excess / (so2_excess + no2_excess + 1.0)
        return {"so2_excess": round(so2_excess, 2), "no2_excess": round(no2_excess, 2), "tectonic_purity": round(tectonic_purity, 3)}

    def _chemical_stress(self) -> float:
        if not self._air_quality:
            return 0.0
        sig = self._degassing_signature()
        so2_excess = sig["so2_excess"]
        tectonic_purity = sig["tectonic_purity"]
        stress = 0.0
        if so2_excess > 5.0:
            stress += min(0.5, (so2_excess / 50.0) * (0.4 + 0.6 * tectonic_purity))
        return min(1.0, stress)

    def _global_node_anomalies(self) -> List[Dict[str, Any]]:
        base = self._degassing_baseline or {}
        base_so2 = base.get("so2", 0.0)
        anomalies = []
        for node in self._global_node_scan:
            tipo = node.get("tipo", "")
            name = node.get("node", "?")
            if tipo in ("VOLCAN", "TECTONICO"):
                so2_excess = max(0.0, node.get("so2", 0.0) - base_so2)
                co = node.get("co", 0.0)
                if so2_excess > self.NODE_SO2_EXCESS_ALERT or co > self.NODE_CO_ALERT:
                    anomalies.append({"node": name, "tipo": tipo, "anomaly": "DEGASSING", "so2_excess": round(so2_excess, 2), "co": co})
            elif tipo == "MARINO":
                temp = node.get("temp_c")
                if temp is not None and temp > self.MARINE_THERMAL_THRESHOLD_C:
                    anomalies.append({"node": name, "tipo": tipo, "anomaly": "MARINE_THERMAL", "temp_c": temp})
        return anomalies

    def analyze(self) -> AgentSignal:
        if not self._pressure_gradient and not self._air_quality and not self._global_node_scan:
            return self.emit_signal(SignalType.NO_SIGNAL, 0.0, reasoning="No atmospheric data")

        figure_analysis = {"match_found": False, "confidence": 0.0}
        if self._current_figure:
            figure_analysis = self._compare_figures(self._current_figure)

        pressure_score = self._pressure_stress()
        chemical_score = self._chemical_stress()
        node_anomalies = self._global_node_anomalies()
        fog_detected = any(
            r.get("visibility_m", 10000) < self.FOG_VISIBILITY_THRESHOLD
            for r in self._atmospheric_readings
        )
        combined_stress = (pressure_score * 0.4) + (chemical_score * 0.4) + min(0.2, len(node_anomalies) * 0.1)

        final_confidence = figure_analysis["confidence"] * 0.7 + combined_stress * 0.3
        effective_confidence = max(final_confidence, combined_stress * 0.75)

        signal_data = {
            "figure_match": figure_analysis["match_found"],
            "similar_mag": figure_analysis.get("similar_magnitude", 0.0),
            "stress_score": combined_stress,
            "pressure_stress": pressure_score,
            "chemical_stress": chemical_score,
            "fog_detected": fog_detected,
            "node_anomalies": node_anomalies,
            "figure_confidence": figure_analysis["confidence"]
        }

        if figure_analysis["match_found"] and effective_confidence > 0.6:
            return self.emit_signal(
                SignalType.ALERT, min(effective_confidence, 0.98),
                data=signal_data,
                reasoning=(
                    f"Cymatic Pattern Match (M{figure_analysis.get('similar_magnitude')}) "
                    f"confirmed by atmospheric stress ({combined_stress:.2f})"
                )
            )

        if effective_confidence > 0.35 or pressure_score > 0.3 or fog_detected:
            return self.emit_signal(
                SignalType.WATCH, min(max(effective_confidence, 0.4), 0.8),
                data=signal_data,
                reasoning=f"Moderate cymatic/atmospheric resonance (score={effective_confidence:.2f})"
            )

        return self.emit_signal(
            SignalType.NEUTRAL, 0.2,
            data=signal_data,
            reasoning="No significant cymatic or atmospheric pattern detected"
        )

    def health_check(self) -> bool:
        return self._pressure_gradient is not None or self._air_quality is not None

