"""
Seed data: 125 topology nodes for the N-Body model.

Node layout (from base_geo.docx):
  - Real nodes (1-50): Major seismic zones, volcanic centers, subduction zones
  - Ghost nodes (51-100): Shadow nodes inferred from geodynamic gaps
  - Geobattery nodes (101-125): Electrochemical accumulation zones

Focus: Mexico + Pacific Ring of Fire + key global seismic zones.
"""

from typing import Dict, List

SEED_NODOS: List[Dict] = [
    # ── Real Nodes: Mexico seismic zones ──────────────────────────
    {"node_id": 1, "nombre": "Guerrero Gap", "lat": 17.2, "lon": -100.5, "tipo": "real", "region": "Mexico", "conductividad": 0.85},
    {"node_id": 2, "nombre": "Oaxaca Costa", "lat": 15.9, "lon": -97.1, "tipo": "real", "region": "Mexico", "conductividad": 0.80},
    {"node_id": 3, "nombre": "Chiapas Subducción", "lat": 14.8, "lon": -92.5, "tipo": "real", "region": "Mexico", "conductividad": 0.75},
    {"node_id": 4, "nombre": "Jalisco-Colima", "lat": 19.2, "lon": -104.0, "tipo": "real", "region": "Mexico", "conductividad": 0.82},
    {"node_id": 5, "nombre": "Michoacán Costa", "lat": 18.0, "lon": -103.0, "tipo": "real", "region": "Mexico", "conductividad": 0.78},
    {"node_id": 6, "nombre": "Puebla-Morelos", "lat": 18.8, "lon": -98.9, "tipo": "real", "region": "Mexico", "conductividad": 0.55},
    {"node_id": 7, "nombre": "CDMX Lago", "lat": 19.4, "lon": -99.1, "tipo": "real", "region": "Mexico", "conductividad": 0.90},
    {"node_id": 8, "nombre": "Popocatépetl", "lat": 19.02, "lon": -98.63, "tipo": "real", "region": "Mexico", "conductividad": 0.70},
    {"node_id": 9, "nombre": "Colima Volcán", "lat": 19.51, "lon": -103.62, "tipo": "real", "region": "Mexico", "conductividad": 0.72},
    {"node_id": 10, "nombre": "Tehuacán", "lat": 18.46, "lon": -97.39, "tipo": "real", "region": "Mexico", "conductividad": 0.60},
    {"node_id": 11, "nombre": "Tlaxcala", "lat": 19.32, "lon": -98.24, "tipo": "real", "region": "Mexico", "conductividad": 0.58},
    {"node_id": 12, "nombre": "Istmo Tehuantepec", "lat": 16.3, "lon": -95.2, "tipo": "real", "region": "Mexico", "conductividad": 0.76},
    {"node_id": 13, "nombre": "Baja California Norte", "lat": 32.5, "lon": -117.0, "tipo": "real", "region": "Mexico", "conductividad": 0.65},
    {"node_id": 14, "nombre": "Baja California Sur", "lat": 24.1, "lon": -110.0, "tipo": "real", "region": "Mexico", "conductividad": 0.60},
    {"node_id": 15, "nombre": "Sonora", "lat": 30.0, "lon": -111.0, "tipo": "real", "region": "Mexico", "conductividad": 0.50},
    # ── Real Nodes: Pacific Ring of Fire ──────────────────────────
    {"node_id": 16, "nombre": "Cascadia", "lat": 46.0, "lon": -124.0, "tipo": "real", "region": "Pacific NW", "conductividad": 0.88},
    {"node_id": 17, "nombre": "San Andreas N", "lat": 37.8, "lon": -122.4, "tipo": "real", "region": "California", "conductividad": 0.85},
    {"node_id": 18, "nombre": "San Andreas S", "lat": 33.9, "lon": -116.5, "tipo": "real", "region": "California", "conductividad": 0.83},
    {"node_id": 19, "nombre": "Alaska Subducción", "lat": 61.0, "lon": -150.0, "tipo": "real", "region": "Alaska", "conductividad": 0.90},
    {"node_id": 20, "nombre": "Kamchatka", "lat": 53.0, "lon": 159.0, "tipo": "real", "region": "Russia", "conductividad": 0.92},
    {"node_id": 21, "nombre": "Japón Nankai", "lat": 33.0, "lon": 135.0, "tipo": "real", "region": "Japan", "conductividad": 0.88},
    {"node_id": 22, "nombre": "Japón Tohoku", "lat": 38.0, "lon": 142.0, "tipo": "real", "region": "Japan", "conductividad": 0.90},
    {"node_id": 23, "nombre": "Filipinas", "lat": 14.5, "lon": 121.0, "tipo": "real", "region": "Philippines", "conductividad": 0.82},
    {"node_id": 24, "nombre": "Indonesia Sumatra", "lat": 2.0, "lon": 99.0, "tipo": "real", "region": "Indonesia", "conductividad": 0.88},
    {"node_id": 25, "nombre": "Indonesia Java", "lat": -7.5, "lon": 110.0, "tipo": "real", "region": "Indonesia", "conductividad": 0.85},
    {"node_id": 26, "nombre": "Tonga-Kermadec", "lat": -20.0, "lon": -175.0, "tipo": "real", "region": "Oceania", "conductividad": 0.80},
    {"node_id": 27, "nombre": "Chile Norte", "lat": -23.0, "lon": -70.0, "tipo": "real", "region": "Chile", "conductividad": 0.87},
    {"node_id": 28, "nombre": "Chile Central", "lat": -33.0, "lon": -72.0, "tipo": "real", "region": "Chile", "conductividad": 0.89},
    {"node_id": 29, "nombre": "Perú Subducción", "lat": -12.0, "lon": -77.0, "tipo": "real", "region": "Peru", "conductividad": 0.84},
    {"node_id": 30, "nombre": "Colombia-Ecuador", "lat": 2.0, "lon": -78.0, "tipo": "real", "region": "South America", "conductividad": 0.80},
    # ── Real Nodes: Other major zones ─────────────────────────────
    {"node_id": 31, "nombre": "Himalaya Nepal", "lat": 28.0, "lon": 85.0, "tipo": "real", "region": "Asia", "conductividad": 0.75},
    {"node_id": 32, "nombre": "Turquía Anatolia", "lat": 39.0, "lon": 36.0, "tipo": "real", "region": "Turkey", "conductividad": 0.78},
    {"node_id": 33, "nombre": "Irán Zagros", "lat": 33.0, "lon": 50.0, "tipo": "real", "region": "Iran", "conductividad": 0.72},
    {"node_id": 34, "nombre": "Italia Apeninos", "lat": 42.0, "lon": 13.0, "tipo": "real", "region": "Europe", "conductividad": 0.68},
    {"node_id": 35, "nombre": "Grecia Helénica", "lat": 37.0, "lon": 22.0, "tipo": "real", "region": "Europe", "conductividad": 0.70},
    {"node_id": 36, "nombre": "Islandia Rift", "lat": 65.0, "lon": -18.0, "tipo": "real", "region": "Atlantic", "conductividad": 0.82},
    {"node_id": 37, "nombre": "Caribe Norte", "lat": 18.5, "lon": -67.0, "tipo": "real", "region": "Caribbean", "conductividad": 0.74},
    {"node_id": 38, "nombre": "Haití-DR", "lat": 18.5, "lon": -72.3, "tipo": "real", "region": "Caribbean", "conductividad": 0.76},
    {"node_id": 39, "nombre": "Nueva Zelanda", "lat": -41.0, "lon": 174.0, "tipo": "real", "region": "Oceania", "conductividad": 0.80},
    {"node_id": 40, "nombre": "Papua NG", "lat": -6.0, "lon": 147.0, "tipo": "real", "region": "Oceania", "conductividad": 0.78},
    {"node_id": 41, "nombre": "Centroamérica", "lat": 13.0, "lon": -88.0, "tipo": "real", "region": "Central America", "conductividad": 0.77},
    {"node_id": 42, "nombre": "Guatemala", "lat": 14.6, "lon": -90.5, "tipo": "real", "region": "Central America", "conductividad": 0.75},
    {"node_id": 43, "nombre": "Hawaii Hotspot", "lat": 19.5, "lon": -155.5, "tipo": "real", "region": "Pacific", "conductividad": 0.65},
    {"node_id": 44, "nombre": "Mid-Atlantic Ridge", "lat": 30.0, "lon": -42.0, "tipo": "real", "region": "Atlantic", "conductividad": 0.70},
    {"node_id": 45, "nombre": "Etna-Sicilia", "lat": 37.75, "lon": 14.99, "tipo": "real", "region": "Europe", "conductividad": 0.72},
    {"node_id": 46, "nombre": "Yellowstone", "lat": 44.4, "lon": -110.6, "tipo": "real", "region": "USA", "conductividad": 0.68},
    {"node_id": 47, "nombre": "Veracruz Costa", "lat": 19.2, "lon": -96.1, "tipo": "real", "region": "Mexico", "conductividad": 0.62},
    {"node_id": 48, "nombre": "Guerrero Interior", "lat": 17.8, "lon": -99.5, "tipo": "real", "region": "Mexico", "conductividad": 0.70},
    {"node_id": 49, "nombre": "Tabasco Delta", "lat": 18.0, "lon": -93.0, "tipo": "real", "region": "Mexico", "conductividad": 0.55},
    {"node_id": 50, "nombre": "Nayarit-Sinaloa", "lat": 22.0, "lon": -105.5, "tipo": "real", "region": "Mexico", "conductividad": 0.58},

    # ── Ghost Nodes: Inferred from seismic gaps ───────────────────
    {"node_id": 51, "nombre": "Ghost Guerrero-Oaxaca", "lat": 16.5, "lon": -98.5, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 52, "nombre": "Ghost Michoacán-Guerrero", "lat": 17.5, "lon": -101.5, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 53, "nombre": "Ghost Chiapas-Guatemala", "lat": 14.2, "lon": -91.5, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 54, "nombre": "Ghost Jalisco-Michoacán", "lat": 18.5, "lon": -103.5, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 55, "nombre": "Ghost Baja-Sonora", "lat": 28.0, "lon": -113.0, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 56, "nombre": "Ghost Cascadia Gap", "lat": 44.0, "lon": -125.0, "tipo": "ghost", "region": "Pacific NW", "conductividad": 0.0},
    {"node_id": 57, "nombre": "Ghost Nankai-Tokai", "lat": 34.5, "lon": 138.0, "tipo": "ghost", "region": "Japan", "conductividad": 0.0},
    {"node_id": 58, "nombre": "Ghost Sumatra-Java", "lat": -4.0, "lon": 104.0, "tipo": "ghost", "region": "Indonesia", "conductividad": 0.0},
    {"node_id": 59, "nombre": "Ghost Chile Gap", "lat": -28.0, "lon": -71.0, "tipo": "ghost", "region": "Chile", "conductividad": 0.0},
    {"node_id": 60, "nombre": "Ghost Perú-Chile", "lat": -18.0, "lon": -72.0, "tipo": "ghost", "region": "South America", "conductividad": 0.0},
    {"node_id": 61, "nombre": "Ghost Alaska-Aleutian", "lat": 55.0, "lon": -165.0, "tipo": "ghost", "region": "Alaska", "conductividad": 0.0},
    {"node_id": 62, "nombre": "Ghost Kamchatka-Kuril", "lat": 48.0, "lon": 153.0, "tipo": "ghost", "region": "Russia", "conductividad": 0.0},
    {"node_id": 63, "nombre": "Ghost Philippines-Taiwan", "lat": 20.0, "lon": 122.0, "tipo": "ghost", "region": "Philippines", "conductividad": 0.0},
    {"node_id": 64, "nombre": "Ghost Tonga-Fiji", "lat": -18.0, "lon": -178.0, "tipo": "ghost", "region": "Oceania", "conductividad": 0.0},
    {"node_id": 65, "nombre": "Ghost Caribbean-PR", "lat": 19.5, "lon": -65.0, "tipo": "ghost", "region": "Caribbean", "conductividad": 0.0},
    {"node_id": 66, "nombre": "Ghost Anatolia E", "lat": 38.0, "lon": 42.0, "tipo": "ghost", "region": "Turkey", "conductividad": 0.0},
    {"node_id": 67, "nombre": "Ghost Himalaya E", "lat": 27.0, "lon": 92.0, "tipo": "ghost", "region": "Asia", "conductividad": 0.0},
    {"node_id": 68, "nombre": "Ghost NZ-Hikurangi", "lat": -39.0, "lon": 178.0, "tipo": "ghost", "region": "Oceania", "conductividad": 0.0},
    {"node_id": 69, "nombre": "Ghost PNG-Solomon", "lat": -8.0, "lon": 155.0, "tipo": "ghost", "region": "Oceania", "conductividad": 0.0},
    {"node_id": 70, "nombre": "Ghost Iceland-Jan Mayen", "lat": 67.0, "lon": -10.0, "tipo": "ghost", "region": "Atlantic", "conductividad": 0.0},
    {"node_id": 71, "nombre": "Ghost Oaxaca Interior", "lat": 16.8, "lon": -96.5, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 72, "nombre": "Ghost Puebla-Veracruz", "lat": 19.0, "lon": -97.5, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 73, "nombre": "Ghost Colima-Jalisco Mar", "lat": 18.5, "lon": -105.0, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 74, "nombre": "Ghost Chiapas Interior", "lat": 15.5, "lon": -93.0, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 75, "nombre": "Ghost San Andreas Mid", "lat": 35.5, "lon": -119.5, "tipo": "ghost", "region": "California", "conductividad": 0.0},
    {"node_id": 76, "nombre": "Ghost Zagros N", "lat": 36.0, "lon": 47.0, "tipo": "ghost", "region": "Iran", "conductividad": 0.0},
    {"node_id": 77, "nombre": "Ghost Colombia Interior", "lat": 4.0, "lon": -75.0, "tipo": "ghost", "region": "South America", "conductividad": 0.0},
    {"node_id": 78, "nombre": "Ghost Guatemala-Honduras", "lat": 15.0, "lon": -89.0, "tipo": "ghost", "region": "Central America", "conductividad": 0.0},
    {"node_id": 79, "nombre": "Ghost Haití Interior", "lat": 19.0, "lon": -71.0, "tipo": "ghost", "region": "Caribbean", "conductividad": 0.0},
    {"node_id": 80, "nombre": "Ghost Mid-Atlantic S", "lat": 10.0, "lon": -40.0, "tipo": "ghost", "region": "Atlantic", "conductividad": 0.0},
    {"node_id": 81, "nombre": "Ghost Mariana", "lat": 15.0, "lon": 147.0, "tipo": "ghost", "region": "Pacific", "conductividad": 0.0},
    {"node_id": 82, "nombre": "Ghost Ryukyu", "lat": 26.0, "lon": 128.0, "tipo": "ghost", "region": "Japan", "conductividad": 0.0},
    {"node_id": 83, "nombre": "Ghost Banda Sea", "lat": -5.0, "lon": 130.0, "tipo": "ghost", "region": "Indonesia", "conductividad": 0.0},
    {"node_id": 84, "nombre": "Ghost Vanuatu", "lat": -16.0, "lon": 168.0, "tipo": "ghost", "region": "Oceania", "conductividad": 0.0},
    {"node_id": 85, "nombre": "Ghost Aleutian W", "lat": 52.0, "lon": 175.0, "tipo": "ghost", "region": "Alaska", "conductividad": 0.0},
    {"node_id": 86, "nombre": "Ghost Chile S", "lat": -42.0, "lon": -73.0, "tipo": "ghost", "region": "Chile", "conductividad": 0.0},
    {"node_id": 87, "nombre": "Ghost Guerrero Deep", "lat": 17.0, "lon": -100.0, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 88, "nombre": "Ghost Tabasco-Campeche", "lat": 18.5, "lon": -92.0, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 89, "nombre": "Ghost Nayarit Offshore", "lat": 21.5, "lon": -106.5, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 90, "nombre": "Ghost Rivera Plate", "lat": 20.0, "lon": -107.0, "tipo": "ghost", "region": "Mexico", "conductividad": 0.0},
    {"node_id": 91, "nombre": "Ghost East Pacific Rise N", "lat": 10.0, "lon": -104.0, "tipo": "ghost", "region": "Pacific", "conductividad": 0.0},
    {"node_id": 92, "nombre": "Ghost East Pacific Rise S", "lat": -15.0, "lon": -113.0, "tipo": "ghost", "region": "Pacific", "conductividad": 0.0},
    {"node_id": 93, "nombre": "Ghost Hindu Kush", "lat": 36.5, "lon": 71.0, "tipo": "ghost", "region": "Asia", "conductividad": 0.0},
    {"node_id": 94, "nombre": "Ghost Myanmar", "lat": 21.0, "lon": 96.0, "tipo": "ghost", "region": "Asia", "conductividad": 0.0},
    {"node_id": 95, "nombre": "Ghost Sunda Strait", "lat": -6.5, "lon": 105.5, "tipo": "ghost", "region": "Indonesia", "conductividad": 0.0},
    {"node_id": 96, "nombre": "Ghost Sulawesi", "lat": -1.0, "lon": 121.0, "tipo": "ghost", "region": "Indonesia", "conductividad": 0.0},
    {"node_id": 97, "nombre": "Ghost Scotia Arc", "lat": -57.0, "lon": -30.0, "tipo": "ghost", "region": "Antarctic", "conductividad": 0.0},
    {"node_id": 98, "nombre": "Ghost East Africa Rift", "lat": -3.0, "lon": 36.0, "tipo": "ghost", "region": "Africa", "conductividad": 0.0},
    {"node_id": 99, "nombre": "Ghost Red Sea Rift", "lat": 20.0, "lon": 38.0, "tipo": "ghost", "region": "Middle East", "conductividad": 0.0},
    {"node_id": 100, "nombre": "Ghost Dead Sea", "lat": 31.5, "lon": 35.5, "tipo": "ghost", "region": "Middle East", "conductividad": 0.0},

    # ── Geobattery Nodes: Electrochemical accumulation zones ──────
    {"node_id": 101, "nombre": "GeoBat Guerrero Sulfuros", "lat": 17.3, "lon": -100.2, "tipo": "geobattery", "region": "Mexico", "conductividad": 0.95},
    {"node_id": 102, "nombre": "GeoBat Oaxaca Grafito", "lat": 16.0, "lon": -96.8, "tipo": "geobattery", "region": "Mexico", "conductividad": 0.92},
    {"node_id": 103, "nombre": "GeoBat Popocatépetl Magma", "lat": 19.0, "lon": -98.6, "tipo": "geobattery", "region": "Mexico", "conductividad": 0.88},
    {"node_id": 104, "nombre": "GeoBat Colima Hidrotermal", "lat": 19.5, "lon": -103.6, "tipo": "geobattery", "region": "Mexico", "conductividad": 0.90},
    {"node_id": 105, "nombre": "GeoBat CDMX Acuífero", "lat": 19.4, "lon": -99.1, "tipo": "geobattery", "region": "Mexico", "conductividad": 0.93},
    {"node_id": 106, "nombre": "GeoBat Cascadia Fluidos", "lat": 45.5, "lon": -124.5, "tipo": "geobattery", "region": "Pacific NW", "conductividad": 0.87},
    {"node_id": 107, "nombre": "GeoBat San Andreas Creep", "lat": 36.0, "lon": -120.5, "tipo": "geobattery", "region": "California", "conductividad": 0.85},
    {"node_id": 108, "nombre": "GeoBat Japón Nankai Fluidos", "lat": 33.5, "lon": 136.0, "tipo": "geobattery", "region": "Japan", "conductividad": 0.90},
    {"node_id": 109, "nombre": "GeoBat Sumatra Hidrotermal", "lat": 1.0, "lon": 98.0, "tipo": "geobattery", "region": "Indonesia", "conductividad": 0.88},
    {"node_id": 110, "nombre": "GeoBat Chile Cobre", "lat": -24.0, "lon": -69.0, "tipo": "geobattery", "region": "Chile", "conductividad": 0.91},
    {"node_id": 111, "nombre": "GeoBat Yellowstone Geyser", "lat": 44.5, "lon": -110.5, "tipo": "geobattery", "region": "USA", "conductividad": 0.86},
    {"node_id": 112, "nombre": "GeoBat Islandia Geotermal", "lat": 64.0, "lon": -20.0, "tipo": "geobattery", "region": "Atlantic", "conductividad": 0.92},
    {"node_id": 113, "nombre": "GeoBat Hawaii Basalto", "lat": 19.4, "lon": -155.3, "tipo": "geobattery", "region": "Pacific", "conductividad": 0.80},
    {"node_id": 114, "nombre": "GeoBat Kamchatka Geyser", "lat": 54.0, "lon": 160.0, "tipo": "geobattery", "region": "Russia", "conductividad": 0.89},
    {"node_id": 115, "nombre": "GeoBat Etna Magma", "lat": 37.7, "lon": 15.0, "tipo": "geobattery", "region": "Europe", "conductividad": 0.84},
    {"node_id": 116, "nombre": "GeoBat Michoacán Sulfuros", "lat": 18.5, "lon": -102.5, "tipo": "geobattery", "region": "Mexico", "conductividad": 0.87},
    {"node_id": 117, "nombre": "GeoBat Chiapas Hidrotermal", "lat": 15.0, "lon": -92.0, "tipo": "geobattery", "region": "Mexico", "conductividad": 0.83},
    {"node_id": 118, "nombre": "GeoBat Tlaxcala Acuífero", "lat": 19.3, "lon": -98.2, "tipo": "geobattery", "region": "Mexico", "conductividad": 0.78},
    {"node_id": 119, "nombre": "GeoBat Veracruz Sedimentos", "lat": 19.1, "lon": -96.0, "tipo": "geobattery", "region": "Mexico", "conductividad": 0.75},
    {"node_id": 120, "nombre": "GeoBat Turquía Geotermal", "lat": 38.5, "lon": 29.0, "tipo": "geobattery", "region": "Turkey", "conductividad": 0.82},
    {"node_id": 121, "nombre": "GeoBat Perú Minerales", "lat": -13.0, "lon": -76.0, "tipo": "geobattery", "region": "Peru", "conductividad": 0.86},
    {"node_id": 122, "nombre": "GeoBat NZ Taupo", "lat": -38.7, "lon": 176.1, "tipo": "geobattery", "region": "Oceania", "conductividad": 0.88},
    {"node_id": 123, "nombre": "GeoBat PNG Rabaul", "lat": -4.3, "lon": 152.2, "tipo": "geobattery", "region": "Oceania", "conductividad": 0.81},
    {"node_id": 124, "nombre": "GeoBat East Africa Rift", "lat": -2.0, "lon": 36.5, "tipo": "geobattery", "region": "Africa", "conductividad": 0.79},
    {"node_id": 125, "nombre": "GeoBat Rivera Plate Deep", "lat": 20.5, "lon": -107.5, "tipo": "geobattery", "region": "Mexico", "conductividad": 0.84},
]


def seed_topology(repo) -> int:
    """Insert all 125 seed nodes into repository. Returns count inserted."""
    return repo.bulk_upsert_nodos(SEED_NODOS)
